### ISSUE TITLE
Remove the need to spin up ephemeral containers to run npm commands locally

### ISSUE THREAD

**Issue by JaneJeon** [JaneJeon/blink#520]
The makefile + docker-compose makes use of the *lack* of dockerfile command in order to automatically shut down the "main" app container (because you can't just say "stand up everything *except* for this one container" with docker-compose), so that everything we run from then on will simply spawn a new ephemeral instance of that app container to run tasks.

That is AWESOME for doing things like testing, where we want to run it without side effects in its own container automatically. However, for development purposes, @jorbecalona noted that the DX is pretty confusing; therefore, the better flow would be to simply docker-compose up all the containers and keep the app container "hanging" in interactive mode by "executing" something like sh, so you can directly run commands from the interactive terminal rather than having to run another make command.

use .env files (e.g. .db.env) to sync config between docker-compose and test!

If we’re hooking into existing running container, also want to make sure we don’t kill it when we exit the shell: https://stackoverflow.com/questions/36249744/interactive-shell-using-docker-compose

**Comment by quentincaffeino** [comment]
> and keep the app container "hanging" in interactive mode by "executing" something like sh

> If we’re hooking into existing running container, also want to make sure we don’t kill it when we exit the shell:

This kinda doesn't make sensee for me because container live as long as it's root process lives. So if you would go `docker run ... sh`, then as soon as you exit that shell proces your container also dies. Of course you could implement something to aleays run in bg as a root process. But isn't it easier just to run the container and then connect to its shell and execute whatever?

**Comment by JaneJeon** [comment]
Yeah I'm new to docker-based development workflows so I'm not really sure what the "best practice" is, but I have this issue up (and am considering this approach) for 2 reasons:
1. Apparently it's confusing that when you `make up`, it's not directly bringing you to the shell of the app container
2. During development, I spin up and kill ephemeral containers often using `make run`, but I noticed that over time I was accumulating a lot of instances of the app container that actually *weren't* killed despite exiting from those containers.

**Comment by JaneJeon** [comment]
Progress: I have managed to re-use an existing container, but it requires me to run it directly w/ docker and not docker-compose. For that, I need to map the volume created by docker compose onto docker directly. WIP

**Comment by JaneJeon** [comment]
So... it's not the volume. Touching some files inside the standalone container does reflect in the host system, so that's fine. It's _still_ erroring w/ 137 (which was why I thought maybe I didn't have the volume mapped correctly), even after I maxed out my memory limit.

**Comment by quentincaffeino** [comment]
> Apparently it's confusing that when you make up, it's not directly bringing you to the shell of the app container

I don't agree with that but ok. It would confuse me if I would appear in the container. I just wanted to bring up the containers why did I end up in the container shell...)

> During development, I spin up and kill ephemeral containers often using make run, but I noticed that over time I was accumulating a lot of instances of the app container that actually weren't killed despite exiting from those containers.

Why do you use `run` when app container already should be running and it is enough to run `exec`?

**Comment by JaneJeon** [comment]
I was really torn on the whole run vs. exec thing. Unfortunately docker compose exec does not seem to respect entrypoint, and to keep the container running you actually need to do some hack like “sleep infinity” to keep the app container.

In the end, the only “downside” about run imho is that it doesn’t clean up anonymous volumes after shutdown, but thats something that can be mitigated by “make down”.

**Comment by quentincaffeino** [comment]
> Unfortunately docker compose exec does not seem to respect entrypoint

And it shouldn't, because container ideally should only have one process (CMD) running and entrypoint is meant to be a base for that. Let's say you would set entrypoint as `node`. Then you want to execute arbitrary shell command inside that container - you won't be able to, because `node /bin/sh` will not work.

> and to keep the container running you actually need to do some hack like “sleep infinity” to keep the app container.

Why do you need it running then if you only use it to execute some tasks? Kill it right after.

**Comment by JaneJeon** [comment]
Hmm, I’ve actually been struggling to come up with a good exec-based workflow. Could you make a PR with a sample Makefile & docker-compose files that would allow the kind of workflow you’re talking about?

**Comment by quentincaffeino** [comment]
If I understand correctly you've practically been doing this:

1. Spin up the containers
2. make run/exec npm dev (or smth like that, because of that you wanted to have it separate)
3. make run/exec ...

Is that right?

**Comment by JaneJeon** [comment]
I've been doing `make up` once, and then using `make run` for local development and tests, and cleaning everything at the end using `make down` (due to the anonymous volumes not being cleaned by docker).

**Comment by quentincaffeino** [comment]
Sorry, I don't have time right now to get to it.
If you're interested in how I do it you can check these two projects of mine:

https://github.com/quentincaffeino/svc-base-docker
https://github.com/quentincaffeino/svc-traefik

First project is a template with all the default files, second is an implementation of it with traefik service.

**Comment by JaneJeon** [comment]
I actually already implemented it in the above PR.
