### ISSUE TITLE
Move to GitHub Actions

### ISSUE THREAD

**Issue by JaneJeon** [JaneJeon/blink#521]
The Dockerfile was built with the build -> test -> deploy workflow in mind (which is why we have multi-stage dockerfile). However, right now we're basically wasting all of the "in-between" steps because of the way CircleCI is structured (where testing with docker-compose or even a custom image is rather... difficult).

Therefore, we should move to GitHub Actions with a docker-compose based CI/CD workflow:
- [ ] lint -> test (frontend & backend) -> build & publish
- [ ] docker-layer caching
- [ ] fail early
- [ ] produce/upload/consume JUnit reports
- [ ] lint image size
- [ ] lint Dockerfile using hadolint

## References
https://github.com/wemake-services/docker-image-size-limit

https://github.com/docker/docker-bench-security

If we sufficiently make this fast enough, we may even be able to remove pre-push testing hook!

**Comment by denzuko** [comment]
If you accept PRs on this, I'll be glad to write up a custom pipeline for you this weekend.
