### ISSUE TITLE
Docker compose v1/v2

### ISSUE THREAD

**Issue by quentincaffeino** [JaneJeon/blink#591]
I left this comment earlier but you haven't responded so I'm not sure you've seen it. So I'm going to repeat it here. At the time of writing (12 days ago) new docker compose wasn't released yet. But overall idea is still the same.

~~New compose cli is still in beta~~, and when it is going to be released not every one will start using it right away. I would suggest checking if it is present and falling back to default docker-compose if not.

```
DC=$(shell test "$(D)" compose >/dev/null 2>/dev/null || false; test "$$?" = "0" && echo "$(D)" compose || echo "$(shell which docker-compose)")
```

**Comment by JaneJeon** [comment]
Hey, I just haven't gotten around to testing it myself yet - I wanna make sure this doesn't break for either the people using compose v1 or compose v2.

**Comment by JaneJeon** [comment]
Yeah… the whole reason we use docker is so that we don’t have “but it works for MY machine!” scenarios, and I’m just not sure how to go about this in a cross-platform compatible manner. I’ll probably just end up recommending people to use dc v2 or modify the $(DC) variable if they use v1.
