### ISSUE TITLE
Deployment instructions unclear for selfhosted docker

### ISSUE THREAD

**Issue by OLEGSHA** [JaneJeon/blink#755]
## Disclaimers

- [x] Before filing this report, I have read the documentation fully and followed it.
- [x] I understand that if the "issue" is something that is already answered by the documentation and/or are caused by me not reading the documentation, the issue *will* be blocked and/or locked (with the implicit explanation being to "go read the docs"), and I may not be able to open another issue for this repository ever again.

## Issue Description

In documentation section [2.3 Installation / Advanced / Docker](https://docs.blink.rest/Installation/2.3%20Advanced#docker), the following command is advised:
```bash
docker run -e DATABASE_URL=... \
    ghcr.io/janejeon/blink:latest npm run db:migrate
```
This command, if run right after pulling the image, results in an error. The cause of this error is difficult to determine for novice users based solely on the stacktrace. According to #754, the problem arises because the environment variables were not set up properly; apparently, a proper `.env` file explained in the Prerequisites section must be configured and mounted inside the container for this command to succeed. While the documentation does have a Note explaining that the following sections are "passing [environment variables] manually for simplicity's sake", nowhere is it mentioned that the commands are pseudocode that won't run if copied and pasted verbatim. Further adding to the confusion, the problematic variable `BASE_URL` is explicitly set in the second command, suggesting it is not necessary for `db:migrate` to run (which I understand it is).

As such, for the sake of users who are scanning over the installation docs for relevant commands (an unstoppable force indeed, trust me) I think it is best to either modify the shell script to make sure it sets everything up if copied and pasted:
```bash
temporary_env=(-e DATABASE_URL=... \
               -e REDIS_URL=... \
               -e HOMEPAGE=... \
               -e BASE_URL=... \
               -e OIDC_CLIENT_ID=... \
               -e OIDC_ISSUER_BASE_URL=...)
docker pull ghcr.io/janejeon/blink:latest
docker run "${temporary_env[@]}" ghcr.io/janejeon/blink:latest npm run db:migrate
docker run "${temporary_env[@]}" ghcr.io/janejeon/blink:latest
```
or mention the additional setup required right in the pseudocode, such that the warning would be visible when pasted:
```bash
docker pull ghcr.io/janejeon/blink:latest
docker run -e (set all environment variables mentioned in Prerequisites section) \
    ghcr.io/janejeon/blink:latest npm run db:migrate
docker run -e (set all environment variables mentioned in Prerequisites section) \
    ghcr.io/janejeon/blink:latest
```

It might also be a good idea in general to add a simple environment check to generate more user-friendly error messages in case the environment is misconfigured.

---

I am creating this issue on behalf of @serega404, the author of #754 and a friend of mine. I saw things were beginning to heat up and decided to intervene before any damage was made.
Sorry for making this into an issue request. I would like to have contacted you directly, but as I understood from your personal blog, you do not wish to receive any private communications.
@serega404 explained (with no small amount of anger) that they have been reading through the documentation extensively for several hours before opening the issue. It is the fact that `BASE_URL` (and other variables) were specifically mentioned in the last command that tripped them up. I completely understand your position on the matter (that one should unconditionally set up a `.env` file before beginning installation), but I'm afraid many users might find this unclear, too.

**Comment by JaneJeon** [comment]
No, I think it was the correct thing to create it as an issue.

I'll just amend the documentation to fill out the appropriate environment variables (see: `.env`), or, your latter pseudocode.

**Comment by JaneJeon** [comment]
There, it's updated in the latest version.
<img width="991" alt="Screenshot 2022-10-07 at 18 50 24" src="https://user-images.githubusercontent.com/24810585/194619259-41c83866-0a29-49d7-951f-2a735ff5a806.png">

Closing this, and please tell your friend - who does not seem to be familiar with Docker workflow - that environment variables _have_ to be supplied; they don't just come out of nowhere (unless you have the `.env` file set up).
