### ISSUE TITLE
Editing Destination

### ISSUE THREAD

**Issue by WillowMist** [JaneJeon/blink#756]
Is there a setting that will let Superusers or the link's creator change the destination of an existing link?  Also, is there a way to generate a QR code with the brand URL, as well as the generated one?

I can circumvent both of these manually (pasting the brand url into an external qr generator) and deleting the original shortened url, and recreate it with a new destination, and then use the brand link qr code.  

But I'd love for our teachers to be able to update the destination on a qr code that they've created for their class.

**Comment by WillowMist** [comment]
Well, the situation in my particular use case is a QR code that is going to be published on billboards and in certain publications.  We want it to redirect to whatever current event we have going on.  Like I said, I have a workaround for this, so it's not critical, by any means.  I just wanted to be sure that I wasn't missing anything.

**Comment by JaneJeon** [comment]
I'm glad it works out for you.
