### ISSUE TITLE
Docker: Blink won't initialize if OIDC provider is still starting up.

### ISSUE THREAD

**Issue by WillowMist** [JaneJeon/blink#757]
**Is your feature request related to a problem? Please describe.**

If running through Docker and also running KeyCloak on docker, Blink tries to connect to the OIDC service before KeyCloak is up and running.  It then fails to start the container.

**Describe the solution you'd like**

It would be nice if there could be a config option that would let it retry connection to OIDC until it succeeds, rather than fail to start entirely.  With luck, the service would still be able to serve already created URLs while it tries.

I've tried to make it depend on keycloak in the docker-compose, but it still starts up before keycloak is responding to requests.

I'm not super-fluent with Node, but I can try to help, if the request makes sense :)

**Comment by JaneJeon** [comment]
Well, Blink expects everything to be "up" by the time it's connected. Connect/retry of OIDC really shouldn't be part of the application, and I suggest putting a short little script (e.g. `wait-on`, `wait-for`, `wait-for-it`) listening to the keycloak endpoint to make sure it is up BEFORE you start Blink.

Making sure "X" is started before "Y" and making sure it satisfies $condition_Z and the like starts to encroach on the boundaries of "orchestration" (e.g. with docker swarm or kubernetes), which is out of scope for this project.

Do look into the "waiting scripts" I pointed out above. They are the _standard_ way ("best practices") of solving this problem, not just across link shorteners, but across cloud-native applications in general.
