### ISSUE TITLE
Can use `-` in brand link but router does not support it

### ISSUE THREAD

**Issue by tomudding** [JaneJeon/blink#797]
## Disclaimers

- [X] Before filing this report, I have read the documentation fully and followed it.
- [X] I understand that if the "issue" is something that is already answered by the documentation and/or are caused by me not reading the documentation, the issue _will_ be blocked and/or locked (with the implicit explanation being to "go read the docs"), and I may not be able to open another issue for this repository ever again.

## Issue Description

**Describe the bug**
When shortening a link, it is possible to use a `-` in the brand link. However, the router (or rather its definition) does not allow this to be matched. This results in `Cannot GET /brand-link`

**Deployment Method**
[Docker](https://docs.blink.rest/Installation/2.3%20Advanced#docker) and PostgreSQL

**To Reproduce**

1. Shorten a new link for `https://example.com`, using `brand-link` for the brand link.
2. The shortened link is correctly created
3. Go to `domain.com/brand-link`
4. Observe `Cannot GET /brand-link`

**Expected behavior**
Going to `domain.com/brand-link` correctly redirects to `https://example.com`

**Screenshots**
N/A

**Additional context**

https://github.com/JaneJeon/blink/blob/a04d7d7665fa96d98d39811bb67f1a1681e9d089/routes/redirect.js#L12
https://github.com/JaneJeon/blink/blob/a04d7d7665fa96d98d39811bb67f1a1681e9d089/config/schema/link.yaml#L16

**Comment by JaneJeon** [comment]
Gotcha. Seems like it should be a quick regex change. I'll get on it soon(TM)

**Comment by JaneJeon** [comment]
And thanks for the detailed report.

**Comment by JaneJeon** [comment]
Actually, this seems not as straightforward as I thought and will require some time for investigation. In particular, while the regex `\w+` indeed doesn't allow for brandlinks with `-` in it, _the same schema is used for validating link shortener's inputs_: https://github.com/JaneJeon/blink/blob/master/src/components/shortener.js#L49

Meaning, according to the schema, you shouldn't have even been able to give it a brandlink with that `-` in it... do you see anything in your browser's console logs when you shorten it with `-` in it?

**Comment by tomudding** [comment]
> Meaning, according to the schema, you shouldn't have even been able to give it a brandlink with that `-` in it... do you see anything in your browser's console logs when you shorten it with `-` in it?

No, after submitting the form the POST request to `domain.com/api/links` returns the following (i.e. a successful creation of shortened link):
![image](https://github.com/JaneJeon/blink/assets/4983571/88912560-152e-4b94-b36b-dab97ea2ce64)

**Comment by JaneJeon** [comment]
Aww man. That means the frontend validator based on the schema is _silently_ failing: https://github.com/JaneJeon/blink/blob/master/src/components/shortener.js#L49

I'll widen the regex to allow `-` as well (just for you), but the source of the issue (the frontend form not adhering to the schema) must be fixed first.

**Comment by JaneJeon** [comment]
Either that, or the script to generate the validators isn't working as intended: https://github.com/JaneJeon/blink/blob/master/scripts/compile-schema.sh

**Comment by tomudding** [comment]
> Aww man. That means the frontend validator based on the schema is _silently_ failing: https://github.com/JaneJeon/blink/blob/master/src/components/shortener.js#L49
>
> Either that, or the script to generate the validators isn't working as intended: https://github.com/JaneJeon/blink/blob/master/scripts/compile-schema.sh

Unfortunately I am not familiar with this way of validating but the length requirements do work (I cannot use a brand link shorter than 4 or longer than 25 characters). So at least part of it works though that does not solve the issue here.

> I'll widen the regex to allow `-` as well (just for you), but the source of the issue (the frontend form not adhering to the schema) must be fixed first.

Awesome! And thanks for looking into this problem so quickly!

**Comment by JaneJeon** [comment]
Okay, confirmed that the generated validator has absolutely janky regex handling, in that it _doesn't work_:
<img width="448" alt="CleanShot 2023-08-18 at 22 42 10@2x" src="https://github.com/JaneJeon/blink/assets/24810585/22c1dc72-5616-48ed-9f64-fee5fb471b70">

(so it's not the frontend; it's the ajv-generated validator)

**Comment by JaneJeon** [comment]
Found this: https://github.com/ajv-validator/ajv/issues/1304

Pushing the fix (which is to add ^ and $)

**Comment by JaneJeon** [comment]
Released: https://github.com/JaneJeon/blink/releases/tag/v1.3.3

https://github.com/JaneJeon/blink/pkgs/container/blink
